pool:
  name: BofiOnPremise2017
trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - /*
    exclude:
    - /*.md 
  tags:
    include:
    - "*"
steps:
- task: UseDotNet@2
  displayName: 'Use .NET version 3.0'
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'

- task: ArtifactoryDotnetCore@1
  displayName: 'Push package to Artifactory'
  inputs:
    command: 'push'
    artifactoryService: 'artifactory'
    targetDeployRepo: 'Bofi.Nuget'
    pathToNupkg: '$(Build.ArtifactStagingDirectory)/*.nupkg'
